package fridalink.service

import fridalink.model.FridaTraceConfig
import java.io.File
import java.util.concurrent.Executors
import java.util.concurrent.atomic.AtomicBoolean

/**
 * Runs frida-trace as a subprocess and streams its output back to a callback.
 *
 * frida-trace generates handler JS files on the fly in __handlers__/ — output
 * shows every call to matched functions with arguments and return values.
 *
 * Usage:
 *   runner.start(config, outputDir) { line -> /* stream line to UI */ }
 *   runner.stop()
 */
class FridaTraceRunner {

    private var process: Process? = null
    private val running = AtomicBoolean(false)
    private val executor = Executors.newCachedThreadPool()

    fun isRunning(): Boolean = running.get()

    /**
     * Start frida-trace with the given config.
     * @param config  FridaTraceConfig with target and patterns
     * @param workDir directory to store generated __handlers__ folder
     * @param onLine  callback invoked on each output line (on a background thread)
     */
    fun start(
        config: FridaTraceConfig,
        workDir: File,
        onLine: (String) -> Unit,
    ) {
        if (running.get()) return
        running.set(true)

        workDir.mkdirs()

        val args = mutableListOf("frida-trace")

        if (config.useSpawn) {
            args += listOf("-f", config.targetPkg)
        } else {
            args += listOf("-n", config.targetPkg)
        }

        // Use USB device (-U) for Android
        args += "-U"

        // Add include patterns
        for (pattern in config.includePatterns) {
            args += listOf("-i", pattern)
        }
        // Add exclude patterns
        for (pattern in config.excludePatterns) {
            args += listOf("-x", pattern)
        }

        // Backtrace — frida-trace supports this via --runtime
        // (not all versions, so we add it only if depth > 0)
        if (config.backtraceDepth > 0) {
            args += listOf("--runtime", "v8")
        }

        onLine("[frida-trace] Starting: ${args.joinToString(" ")}")

        try {
            val pb = ProcessBuilder(args)
            pb.directory(workDir)
            pb.redirectErrorStream(true)  // merge stderr into stdout
            process = pb.start()

            // Read stdout on a background thread
            executor.submit {
                try {
                    process!!.inputStream.bufferedReader().use { reader ->
                        reader.lines().forEach { line ->
                            onLine(line)
                        }
                    }
                } catch (_: Exception) {}
                running.set(false)
                onLine("[frida-trace] Process exited")
            }
        } catch (e: Exception) {
            running.set(false)
            onLine("[frida-trace] ERROR: ${e.message}")
            onLine("[frida-trace] Make sure frida-trace is installed: pip install frida-tools")
        }
    }

    fun stop() {
        running.set(false)
        try { process?.destroyForcibly() } catch (_: Exception) {}
        process = null
    }

    /**
     * Build a minimal handler script for a given function pattern that logs
     * all arguments and return values.  Users can customize the generated
     * __handlers__/<lib>/<fn>.js files for manipulation.
     */
    fun buildHandlerTemplate(functionName: String, libName: String): String = """
/*
 * Frida Trace handler for ${libName}!${functionName}
 * Generated by FridaLink. Modify to intercept and manipulate values.
 *
 * To modify return value:
 *   retval.replace(ptr("0x0")); // force return 0
 *
 * To modify argument:
 *   args[1] = ptr("0x1234");
 */
{
  onEnter(log, args, state) {
    log('${functionName}()');
    // log('  arg0:', args[0]);
    // log('  arg1:', args[1]);
  },
  onLeave(log, retval, state) {
    log('${functionName}() => ' + retval);
    // retval.replace(ptr("0x1")); // uncomment to force retval = 1
  }
}
""".trimIndent()
}
